DATA:
  name: "UKW256"
  img_size: 256
  num_classes: 60
PRE:
  apply_rflip: True
MODEL:
  backbone: "big_resnet"
  g_cond_mtd: "cBN"
  d_cond_mtd: "AC"
  aux_cls_type: "ADC"
  normalize_d_embed: True
  d_embed_dim: 768
  apply_g_sn: True
  apply_d_sn: True
  apply_attn: True
  attn_g_loc: [5]
  attn_d_loc: [1]
  z_dim: 140
  g_shared_dim: 128
  g_conv_dim: 32
  d_conv_dim: 32
  apply_g_ema: True
  g_ema_decay: 0.9999
  g_ema_start: 1000
LOSS:
  adv_loss: "hinge"
  cond_lambda: 1
OPTIMIZATION:
  batch_size: 16
  acml_steps: 4
  g_lr: 0.00005
  d_lr: 0.0002
  beta1: 0.0
  beta2: 0.999
  d_updates_per_step: 2
  total_steps: 20000
AUG:
  apply_diffaug: True
  diffaug_type: "diffaug"
